### ISSUE TITLE
Issue#40-integrate front end w/ back end

### ISSUE THREAD

**Issue by max-opps** [Freddy444/Songrating-Freddy.Max#76]
Sending HTTP requests from your frontend to the backend is crucial. You can use an HTTP
request library like Axios (https://axios-http.com/) or React fetch to achieve this. You can
import axios using import axios from "axios"; and then, for example: [see picture on #4 in hw 3]

**Comment by Freddy444** [comment]
Implement HTTP requests from the frontend to the backend using Axios or React fetch.

**Comment by Freddy444** [comment]
Ensure seamless communication between the React app and the PHP/MySQL backend.
