### ISSUE TITLE
Issue#44-Add at least 1 additional feature

### ISSUE THREAD

**Issue by max-opps** [Freddy444/Songrating-Freddy.Max#80]
Here are some feature suggestions:
- Add Sort or Search Functionality, e.g., search for all songs from a particular artist or with an
average rating above a certain threshold.
- Add Playlists. Add functionality for users to create custom lists, e.g., similar to playlists on Spotify.
- Add Statistics. Add lists with top rated songs, average song ratings, number of songs per artist,
etc.
- Add Tooltips or React notifications (https://www.npmjs.com/package/react-notifications), e.g.,
in case of duplicates.
- Add Functionality for Actually Playing Songs. Please only use royalty-free music, e.g., from
https://cchound.com/. Big Feature for those that get going when the going gets tough :)
- Add Functionality for Commenting. For example, it may be possible to allow users to add
comment on the songs and other users would be able to react (vote/disagree) with existing
comments. Note, it would not be sufficient to just add a comment field to a song.

**Comment by Freddy444** [comment]
THE ACTUAL IMPLEMENTED NEW FEATURE

Displays various statistics:
Username.
Top-rated song and artist.
Total number of songs.
Top-rated genre.
Total number of user ratings.
Render Method:
